export const CHANGE_SEARCHFIELD = "CHANGE_SEARCHFIELD";

export const ROBOTS_REQUEST_PENDING = "ROBOTS_REQUEST_PENDING";
export const ROBOTS_REQUEST_SUCCESS = "ROBOTS_REQUEST_SUCCESS";
export const ROBOTS_REQUEST_FAILED = "ROBOTS_REQUEST_FAILED";
